### ISSUE TITLE
web frameworkの選定

### ISSUE THREAD

**Issue by eniehack** [technopolis-microblog/Technopolis#1]
05/21 03:33 do
追記: attainに決定
end

完全にAPI方式にするのか、またはHTMLを配信するのかにも依るとは思うけど、とりあえず https://deno.land/x/ にあるものをだいたい列挙した。

- [abc](https://deno.land/x/abc)
- [alosaur](https://deno.land/x/alosaur)
- [aqua](https://deno.land/x/aqua)
- [attain](https://deno.land/x/attain)
- [denotrain](https://deno.land/x/denotrain)
- [espresso](https://deno.land/x/espresso)
- [fastro](https://deno.land/x/fastro)
- [pogo](https://deno.land/x/pogo)
- [fen](https://deno.land/x/fen)
- [dinja](https://deno.land/x/dinja)

ちなみに標準パッケージにも [http](https://deno.land/std/http) がある

**Comment by silverscat-3** [comment]
とりあえず、暫定でAttainにしておく。(本当はaquaにしたいんだけど、Routerがないのはちょっと辛い)

**Comment by eniehack** [comment]
README参照する限りaquaにもルータあるくない？

**Comment by silverscat-3** [comment]
> README参照する限りaquaにもルータあるくない？
なんだろうな、こういうことをしたいんだけど、aquaには無さそうなんだよね…

```
const api = new Router();

const sampleMiddleware = (req: Request, res: Response) => {
  console.log("before send")
};

api.use(sampleMiddleware, (req, res) => {
  res.status(200).send({status: "Good"});
});



```

**Comment by eniehack** [comment]
あ、Middlewareってこと？

**Comment by silverscat-3** [comment]
Application以外にもRouterでルーティングができて、それぞれに個別にmiddlewareを設定できる感じ

**Comment by eniehack** [comment]
なるほど。

**Comment by eniehack** [comment]
じゃあattain？

**Comment by silverscat-3** [comment]
とりあえずそういうことで

**Comment by silverscat-3** [comment]
Attainが謎のリポジトリを参照して動作しない(全ギレ)なので再選

**Comment by silverscat-3** [comment]
試したところ、oakが良さげな感じなのでこれを採用してみる
