### ISSUE TITLE
Elmのビルドをどうやるか

### ISSUE THREAD

**Issue by eniehack** [technopolis-microblog/Technopolis#10]
フロントエンドでElmを採用するとしてどうビルドするか？

npmパッケージではただコンパイラの最新版をReleaseからもってきて解凍してるだけっぽいけど、Denoではgzipやminifyライブラリが無いので両方あるRubyに投げようかなと思っている

## 参考リンク
* [uglifier](https://github.com/lautis/uglifier) - rubyにugifyjsをポートしたもの
* [library zlib (Ruby 2.7.0 リファレンスマニュアル)](https://docs.ruby-lang.org/ja/latest/library/zlib.html)

**Comment by silverscat-3** [comment]
denoくん、gzipライブラリ無いのか…辛いなぁ

まぁそれでいいんじゃないかなって思います(クソ適当)

**Comment by eniehack** [comment]
WASMでならgzipを解凍できるんだけど、Elmが生成したJSをminifyしたいけどどうもなさそうなので……
