### ISSUE TITLE
API or SSR

### ISSUE THREAD

**Issue by eniehack** [technopolis-microblog/Technopolis#5]
完全にAPIで対処するか（OAuthはもちろんサーバサイドレンダリングになりそうだけど）、サーバーでHTMLもレンダリングするスタイル（WordPressみたいな感じ）にするか

APIならばSwaggerでドキュメントがほしい

**Comment by silverscat-3** [comment]
ショボいクライアントでも動作させたいのでできる限りSSRで行きたいところ

**Comment by eniehack** [comment]
APIならフロントとバックの開発が分離でき、バックエンドはAPIの開発にだけ専念できるがどうだろうか

**Comment by silverscat-3** [comment]
う~ん…それもそうだなぁ

フロントエンド開発できる人居ますか?

**Comment by eniehack** [comment]
デザイン案さえあればElmで書くぞ。デザイン案ないなら考えるが

**Comment by silverscat-3** [comment]
デザイン案は…特に無い! SlackとTweetdeckを足して2で割った感じ?

**Comment by eniehack** [comment]
takimuraさんも主張してるけどやっぱDeck機能欲しいんです？

**Comment by silverscat-3** [comment]
@eniehack いろんなタイムラインを並べて見たい。
カスタムTLを実装するまでは後回しでいいかもしれない

**Comment by eniehack** [comment]
まあそうね、それまではシングルカラムだけでもいいかもね。それだけなら多分実装できる。APiで疎結合にするなら尚更API docが欲しいところ

**Comment by eniehack** [comment]
frontとbackのリポジトリを分離するならbackにfrontをsubmoduleとして導入するとかしたほうがいいかも

**Comment by eniehack** [comment]
すまん、一部分でSSRを導入しないとSEO対策が面倒かもしれない
